### ISSUE TITLE
Find API or source of data for trip data

### ISSUE THREAD

**Issue by bmurdata** [bmurdata/wonderhop#3]

**Comment by bmurdata** [comment]
Once source SimpleMaps: https://simplemaps.com/data/us-cities
US Gov: https://catalog.data.gov/dataset?tags=cities

**Comment by zmor-prog** [comment]
Possible resources of use:
https://www.tripadvisor.com/developers
https://openweathermap.org/api
https://developers.amadeus.com/
https://github.com/public-api-lists/public-api-lists#transportation

**Comment by bmurdata** [comment]
Thanks, will review!
